#define MSG_LENGTH_MAX 256

#define LOOKAT_WORD_LOOK_AROUND      (ID_LOOK_AT + 0x01)

#define MOTION_WORD_MOTION_START     (ID_MOTION_SENSOR + 0x01)
#define MOTION_WORD_MOTION_END       (ID_MOTION_SENSOR + 0x02)

#define THUNDER_WORD_RRRRR           (ID_THUNDER + 0x01)

#define ROCKING_WORD_ROCK_ROCK_ROCK  (ID_ROCKING + 0x01)

#define DISTANCE_WORD_ARRIVED        (ID_DISTANCE + 0x01)
#define DISTANCE_WORD_LEFT           (ID_DISTANCE + 0x02)

#define BAG_WORD_HANDLE_UP           (ID_BAG + 0x01)
#define BAG_WORD_HANDLE_DOWN         (ID_BAG + 0x02)
#define BAG_WORD_SING                (ID_BAG + 0x03)

#define HARMONICA_WORD_PLAY_START    (ID_HARMONICA + 0x01)
#define HARMONICA_WORD_PLAY_STOP     (ID_HARMONICA + 0x02)

#define FUR_WORD_SING                (ID_FUR + 0x01)

#define KEYHOLDER_WORD_FALLING_KEYS  (ID_KEYHOLDER + 0x01)

#define MIRROR_WORD_IWILLSHOWYOU     (ID_MIRROR + 0x01)

#define PEAK_WORD_PPI_PPI_PPI        (ID_PEAK + 0x01)

#define BELL_WORD_RING_RING_RING     (ID_BELL + 0x01)

#define FLOAT_WORD_TURN_TURN         (ID_FLOAT + 0x01)

#define HEATER_WORD_NOISY_NOISY      (ID_HEATER + 0x01)

#define GPS_WORD_PLANETARY_ANNOUNCEMENT   (ID_GPS + 0x01)

#define DOOR_WORD_PASSING_BY         (ID_DOOR + 0x01)
#define DOOR_WORD_NO_PASSENGER       (ID_DOOR + 0x02)
