#define MSG_LENGTH_MAX 256

#define LOOKAT_WORD_LOOK_AROUND  (ID_LOOK_AT + 0x01)

#define MOTION_WORD_MOTION_START (ID_MOTION_SENSOR + 0x01)
#define MOTION_WORD_MOTION_END   (ID_MOTION_SENSOR + 0x02)

#define THUNDER_WORD_RRRRR       (ID_THUNDER + 0x01)

#define ROCKING_WORD_ROCK_ROCK_ROCK      (ID_ROCKING + 0x01)

#define DISTANCE_WORD_ARRIVED      (ID_DISTANCE + 0x01)
#define DISTANCE_WORD_LEFT         (ID_DISTANCE + 0x02)

#define BAG_WORD_HANDLE_UP       (ID_BAG + 0x01)
#define BAG_WORD_HANDLE_DOWN     (ID_BAG + 0x02)
#define BAG_WORD_SING            (ID_BAG + 0x03)
