#define MSG_LENGTH_MAX 256

#define LOOKAT_WORD_LOOK_AROUND (ID_LOOK_AT + 0x01)
#define LOOKAT_WORD_LOOK_AROUND (ID_LOOK_AT + 0x01)

#define MOTION_WORD_MOTION_START (ID_MOTION_SENSOR + 0x01)
#define MOTION_WORD_MOTION_END   (ID_MOTION_SENSOR + 0x02)
